import NavbarWrapper from "@/components/NavbarWrapper";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
        <NavbarWrapper />
        <main>{children}</main>

    </>
  );
}
