import "./globals.css";
import Authprovider from "@/context/authprovider";
import FooterWrapper from "@/components/FooterWrapper";
import NavbarWrapper from "@/components/NavbarWrapper";
import { Toaster } from "@/components/ui/sonner"
import { SpeedInsights } from "@vercel/speed-insights/next"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#FDFAF6] text-[#2B2B2B] flex flex-col min-h-screen`}>
        <Authprovider>
          <NavbarWrapper />
          <SpeedInsights/>
          <main className="flex-grow">
            {children}
          </main>
          <Toaster />
          <FooterWrapper />
        </Authprovider>
      </body>
    </html>
  );
}